[package]
name = "btcstudy"
version = "0.1.0"
authors = ["leedy <yulidaiahx@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.10.1"
hex = "0.4"
